
input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"
node {
    name: "T2sExecutor"
    calculator: "T2sCalculator"
    input_side_packet: "TTS_NODE_RESOURCES:t2s_servable"
    input_stream: "HTTP_REQUEST_PAYLOAD:input"
    output_stream: "HTTP_RESPONSE_PAYLOAD:output"
    node_options: {
        [type.googleapis.com / mediapipe.T2sCalculatorOptions]: {
            models_path: "{{MODELS}}/Kokoro-82M-int8-ov"
            target_device: "CPU"
            plugin_config: '{"NUM_STREAMS":"1"}'
            }
    }
}
