
input_stream: "REQUEST_PAYLOAD:input"
output_stream: "RESPONSE_PAYLOAD:output"
node {
    name: "EmbeddingsExecutor"
    calculator: "EmbeddingsCalculatorOV"
    input_side_packet: "EMBEDDINGS_NODE_RESOURCES:embeddings_servable"
    input_stream: "REQUEST_PAYLOAD:input"
    output_stream: "RESPONSE_PAYLOAD:output"
    node_options: {
        [type.googleapis.com / mediapipe.EmbeddingsCalculatorOVOptions]: {
            models_path: "{{MODELS}}/Qwen3-Embedding-0.6B-int8-ov",
            normalize_embeddings: true,
            truncate: true,
            max_length: 512,
            pooling: LAST,
            target_device: "CPU",
            plugin_config: '{"NUM_STREAMS":"1","CACHE_DIR":"{{CACHE}}"}',
        }
    }
}
